### PR TITLE
[BUGFIX] Fix latched cvar strings in console to show pending value instead of broken text

### LINKED ISSUE #798: [BUG] Changing a non-boolean latched cvar and checking what it will change to doesn't show the new value in console
**Describe the bug**
If you change a non-boolean latched cvar in console and then check what it will be changed to, the console doesn't print the new value.

**Build that the bug occurred in**
Odamex v10.2.0

**To Reproduce**
Open console, change a non-boolean latched cvar, check what it will be changed to before it's had a chance to be changed.

**Expected behavior**
Typing in the cvar again should actually show what value it will be changed to for non-boolean cvars.

**Screenshots, NetDemos, & Crash Dumps**
https://puu.sh/JqwZJ/fce7970219.png
https://puu.sh/Jqx3b/67ee397165.png

**Additional context**

### PR DESCRIPTION
**Pull request by bcahue**
Due to how strings were expressed for latched cvar pending change retrieval, they'd create broken strings every time. I fixed this behavior by making the pending change a string from the beginning.

Old behavior:
image

New behavior: 
image

Fixes #798

### CODE REVIEW

File: common/c_cvars.cpp [hunk 1]
```diff
@@ -612,12 +612,12 @@ static std::string C_GetLatchedValueString(const cvar_t* var)
 		return C_GetValueString(var);
 
 	if (var->flags() & CVAR_NOENABLEDISABLE)
-		return '"' + var->latched() + '"';
+		return '"' + std::string(var->latched()) + '"';
```
Comment (leximayfield) [inline common/c_cvars.cpp]: Yeah, chars are actually considered numeric types according to C.

I am still not a fan of what's going on here, though.  I think this would be much better off as a `StrFormat` instead of doing string concatenation.

**Review by leximayfield — CHANGES_REQUESTED** [review]

File: common/c_cvars.cpp (hunk 1 above)
Comment (bcahue) [reply common/c_cvars.cpp]: Done, changed to use StrFormat and verified functionality:

image

**Review by leximayfield — APPROVED** [review]
LGTM
